name: Claude Code Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude-assistant:
    runs-on: ubuntu-latest
    name: Claude Code Assistant
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Claude Code Assistant
        uses: anthropics/claude-code@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: 'assistant'
          
          # Context about the project
          project-context: |
            This is a Model Context Protocol (MCP) server that provides calendar and reminder management 
            for macOS using EventKit and PyObjC. The server enables natural language interaction with 
            macOS Calendar and Reminders apps through Claude Desktop or other MCP clients.
            
            Key technologies:
            - Python 3.12+
            - PyObjC for EventKit integration
            - MCP (Model Context Protocol)
            - FastMCP for server implementation
            
            Main functionality:
            - Calendar event CRUD operations
            - Reminder CRUD operations  
            - Natural language date/time parsing
            - Recurrence rules and alarms
            - Multi-calendar support
          
          # Enable various assistant capabilities
          capabilities: |
            code-explanation
            bug-analysis
            feature-suggestions
            documentation-help
            troubleshooting
            code-generation
            refactoring-suggestions